# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: chaudhari.sushmita@gmail.com
brand: Sushmita Chaudhari
headline: Web Developer, Amateur Photographer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "https://sushmita21.github.io/blog" # the subpath of your site, e.g. /blog
url: "https://sushmita21.github.io" # the base hostname & protocol for your site
copyright: 2017 Sushmita Chaudhari. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552
instagram: sushmitacha
# Contacts
email: chaudhari.sushmita@gmail.com
phone: +1-617-309-6035

# Tracking
googleAnalitycsID: UA-83933844-1

